on:
  push:
    branches: [ master ]

jobs:
  til:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating TIL page
        id: til
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'zola'
          cli: 'build'
          infile: ''
          outfile: ''