on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '40 * * * *'

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating word-cloud
        id: wcloud
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'wcloud'
          cli: '--height 286 --width 780 --font fonts/FinkHeavy.ttf '
          infile: 'cloud2.md'
          outfile: 'header.png'
      - name: Colorize Image
        id: colorize
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'sic -i ./images/header.png --invert -o ./images/header.png'
          cli: ''
      - name: Generating pages
        id: buildpages
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'zola build'
          cli: ''
      - name: Pushing pages
        id: pushpages
        uses: mborejdo/action-rusty@refs/heads/master
        env:
          REPO: mborejdo.github.io
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          mode: 'deno run -A --quiet ./index.ts'
          cli: ''